name: Cutter
title: Cutter

project:
  version: 1.7.4
  download_url: https://github.com/radareorg/cutter/releases

license:
  software: GPLv3
  software_url: https://opensource.org/licenses/GPL-3.0

  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/

git_edit_address: https://github.com/radareorg/cutter/tree/master/docs

links:
  header:
    - title: GitHub
      url: https://github.com/radareorg/cutter
  footer:
    - title: GitHub
      url: https://github.com/radareorg/cutter
    - title: Issues
      url: https://github.com/radareorg/cutter/issues

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
  github:
    user: radareorg
    repo: cutter
  twitter:
    enabled: false
    via: r2gui
    hash:
    account: r2gui

disqus: false

description: >-
  Cutter is a Qt and C++ graphical user interface for the reverse
  engineering framework radare2.

# Build settings
markdown: kramdown
remote_theme: radareorg/cutter-jekyll-docs-theme

plugins:
  - jekyll-remote-theme
